# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLCDNumber, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(826, 800)
        self.Channel2_frame = QFrame(Main)
        self.Channel2_frame.setObjectName(u"Channel2_frame")
        self.Channel2_frame.setGeometry(QRect(20, 330, 281, 221))
        font = QFont()
        font.setBold(True)
        self.Channel2_frame.setFont(font)
        self.Channel2_frame.setAutoFillBackground(True)
        self.Channel2_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Channel2_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Channe2_Voltage_LCD_2 = QLCDNumber(self.Channel2_frame)
        self.Channe2_Voltage_LCD_2.setObjectName(u"Channe2_Voltage_LCD_2")
        self.Channe2_Voltage_LCD_2.setGeometry(QRect(140, 60, 71, 23))
        self.Channe2_Current_LCD_2 = QLCDNumber(self.Channel2_frame)
        self.Channe2_Current_LCD_2.setObjectName(u"Channe2_Current_LCD_2")
        self.Channe2_Current_LCD_2.setGeometry(QRect(140, 90, 71, 23))
        self.Channel2_Power_LCD_2 = QLCDNumber(self.Channel2_frame)
        self.Channel2_Power_LCD_2.setObjectName(u"Channel2_Power_LCD_2")
        self.Channel2_Power_LCD_2.setGeometry(QRect(140, 120, 121, 23))
        self.Channe2_Energy_LCD_2 = QLCDNumber(self.Channel2_frame)
        self.Channe2_Energy_LCD_2.setObjectName(u"Channe2_Energy_LCD_2")
        self.Channe2_Energy_LCD_2.setGeometry(QRect(140, 150, 121, 23))
        self.Channe2_Reset_pushButton_2 = QPushButton(self.Channel2_frame)
        self.Channe2_Reset_pushButton_2.setObjectName(u"Channe2_Reset_pushButton_2")
        self.Channe2_Reset_pushButton_2.setGeometry(QRect(190, 190, 80, 24))
        self.lineEdit_6 = QLineEdit(self.Channel2_frame)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(10, 120, 61, 24))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_7 = QLineEdit(self.Channel2_frame)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(10, 10, 71, 41))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_8 = QLineEdit(self.Channel2_frame)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(10, 90, 61, 24))
        self.lineEdit_8.setReadOnly(True)
        self.Channe2_Start_pushButton_2 = QPushButton(self.Channel2_frame)
        self.Channe2_Start_pushButton_2.setObjectName(u"Channe2_Start_pushButton_2")
        self.Channe2_Start_pushButton_2.setGeometry(QRect(10, 190, 80, 24))
        self.lineEdit_9 = QLineEdit(self.Channel2_frame)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(10, 60, 61, 24))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_10 = QLineEdit(self.Channel2_frame)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(10, 150, 61, 24))
        self.lineEdit_10.setReadOnly(True)
        self.Channe2_Pause_pushButton_2 = QPushButton(self.Channel2_frame)
        self.Channe2_Pause_pushButton_2.setObjectName(u"Channe2_Pause_pushButton_2")
        self.Channe2_Pause_pushButton_2.setGeometry(QRect(100, 190, 80, 24))
        self.Channele3_frame = QFrame(Main)
        self.Channele3_frame.setObjectName(u"Channele3_frame")
        self.Channele3_frame.setGeometry(QRect(20, 560, 281, 221))
        self.Channele3_frame.setFont(font)
        self.Channele3_frame.setAutoFillBackground(True)
        self.Channele3_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Channele3_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Channe3_Voltage_LCD_3 = QLCDNumber(self.Channele3_frame)
        self.Channe3_Voltage_LCD_3.setObjectName(u"Channe3_Voltage_LCD_3")
        self.Channe3_Voltage_LCD_3.setGeometry(QRect(140, 60, 71, 23))
        self.Channe3_Current_LCD_3 = QLCDNumber(self.Channele3_frame)
        self.Channe3_Current_LCD_3.setObjectName(u"Channe3_Current_LCD_3")
        self.Channe3_Current_LCD_3.setGeometry(QRect(140, 90, 71, 23))
        self.Channel3_Power_LCD_3 = QLCDNumber(self.Channele3_frame)
        self.Channel3_Power_LCD_3.setObjectName(u"Channel3_Power_LCD_3")
        self.Channel3_Power_LCD_3.setGeometry(QRect(140, 120, 121, 23))
        self.Channe3_Energy_LCD_3 = QLCDNumber(self.Channele3_frame)
        self.Channe3_Energy_LCD_3.setObjectName(u"Channe3_Energy_LCD_3")
        self.Channe3_Energy_LCD_3.setGeometry(QRect(140, 150, 121, 23))
        self.Channe3_Reset_pushButton_3 = QPushButton(self.Channele3_frame)
        self.Channe3_Reset_pushButton_3.setObjectName(u"Channe3_Reset_pushButton_3")
        self.Channe3_Reset_pushButton_3.setGeometry(QRect(190, 190, 80, 24))
        self.lineEdit_11 = QLineEdit(self.Channele3_frame)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(10, 120, 61, 24))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_12 = QLineEdit(self.Channele3_frame)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(10, 10, 71, 41))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_13 = QLineEdit(self.Channele3_frame)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(10, 90, 61, 24))
        self.lineEdit_13.setReadOnly(True)
        self.Channe3_Start_pushButton_3 = QPushButton(self.Channele3_frame)
        self.Channe3_Start_pushButton_3.setObjectName(u"Channe3_Start_pushButton_3")
        self.Channe3_Start_pushButton_3.setGeometry(QRect(10, 190, 80, 24))
        self.lineEdit_14 = QLineEdit(self.Channele3_frame)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(10, 60, 61, 24))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_15 = QLineEdit(self.Channele3_frame)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(10, 150, 61, 24))
        self.lineEdit_15.setReadOnly(True)
        self.Channe3_Pause_pushButton_3 = QPushButton(self.Channele3_frame)
        self.Channe3_Pause_pushButton_3.setObjectName(u"Channe3_Pause_pushButton_3")
        self.Channe3_Pause_pushButton_3.setGeometry(QRect(100, 190, 80, 24))
        self.Connection_frame = QFrame(Main)
        self.Connection_frame.setObjectName(u"Connection_frame")
        self.Connection_frame.setGeometry(QRect(20, 10, 281, 81))
        self.Connection_frame.setFont(font)
        self.Connection_frame.setAutoFillBackground(True)
        self.Connection_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Connection_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.lineEdit_21 = QLineEdit(self.Connection_frame)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(10, 10, 91, 31))
        self.lineEdit_21.setReadOnly(True)
        self.comboBox = QComboBox(self.Connection_frame)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 50, 101, 24))
        self.pushButton = QPushButton(self.Connection_frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(120, 50, 80, 24))
        self.pushButton_2 = QPushButton(self.Connection_frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(120, 10, 80, 24))
        self.Channel1_frame = QFrame(Main)
        self.Channel1_frame.setObjectName(u"Channel1_frame")
        self.Channel1_frame.setGeometry(QRect(20, 100, 281, 221))
        self.Channel1_frame.setFont(font)
        self.Channel1_frame.setAutoFillBackground(True)
        self.Channel1_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Channel1_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Channe1_Voltage_LCD = QLCDNumber(self.Channel1_frame)
        self.Channe1_Voltage_LCD.setObjectName(u"Channe1_Voltage_LCD")
        self.Channe1_Voltage_LCD.setGeometry(QRect(140, 60, 71, 23))
        self.Channe1_Current_LCD = QLCDNumber(self.Channel1_frame)
        self.Channe1_Current_LCD.setObjectName(u"Channe1_Current_LCD")
        self.Channe1_Current_LCD.setGeometry(QRect(140, 90, 71, 23))
        self.Channel1_Power_LCD = QLCDNumber(self.Channel1_frame)
        self.Channel1_Power_LCD.setObjectName(u"Channel1_Power_LCD")
        self.Channel1_Power_LCD.setGeometry(QRect(140, 120, 121, 23))
        self.Channe1_Energy_LCD = QLCDNumber(self.Channel1_frame)
        self.Channe1_Energy_LCD.setObjectName(u"Channe1_Energy_LCD")
        self.Channe1_Energy_LCD.setGeometry(QRect(140, 150, 121, 23))
        self.Channe1_Reset_pushButton = QPushButton(self.Channel1_frame)
        self.Channe1_Reset_pushButton.setObjectName(u"Channe1_Reset_pushButton")
        self.Channe1_Reset_pushButton.setGeometry(QRect(190, 190, 80, 24))
        self.lineEdit_3 = QLineEdit(self.Channel1_frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 120, 61, 24))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.Channel1_frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 10, 101, 41))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_2 = QLineEdit(self.Channel1_frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 90, 61, 24))
        self.lineEdit_2.setReadOnly(True)
        self.Channe1_Start_pushButton = QPushButton(self.Channel1_frame)
        self.Channe1_Start_pushButton.setObjectName(u"Channe1_Start_pushButton")
        self.Channe1_Start_pushButton.setGeometry(QRect(10, 190, 80, 24))
        self.lineEdit = QLineEdit(self.Channel1_frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 60, 61, 24))
        self.lineEdit.setReadOnly(True)
        self.lineEdit_5 = QLineEdit(self.Channel1_frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 150, 61, 24))
        self.lineEdit_5.setReadOnly(True)
        self.Channe1_Pause_pushButton = QPushButton(self.Channel1_frame)
        self.Channe1_Pause_pushButton.setObjectName(u"Channe1_Pause_pushButton")
        self.Channe1_Pause_pushButton.setGeometry(QRect(100, 190, 80, 24))
        self.Database_Tab = QTabWidget(Main)
        self.Database_Tab.setObjectName(u"Database_Tab")
        self.Database_Tab.setGeometry(QRect(310, 140, 511, 641))
        self.Database_Tab.setIconSize(QSize(16, 16))
        self.Channel1 = QWidget()
        self.Channel1.setObjectName(u"Channel1")
        self.tableWidget = QTableWidget(self.Channel1)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 551, 651))
        self.Database_Tab.addTab(self.Channel1, "")
        self.Channel2 = QWidget()
        self.Channel2.setObjectName(u"Channel2")
        self.tableWidget_2 = QTableWidget(self.Channel2)
        if (self.tableWidget_2.columnCount() < 5):
            self.tableWidget_2.setColumnCount(5)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(0, 0, 511, 651))
        self.Database_Tab.addTab(self.Channel2, "")
        self.Channel3 = QWidget()
        self.Channel3.setObjectName(u"Channel3")
        self.tableWidget_3 = QTableWidget(self.Channel3)
        if (self.tableWidget_3.columnCount() < 5):
            self.tableWidget_3.setColumnCount(5)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, __qtablewidgetitem14)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(0, 0, 511, 651))
        self.Database_Tab.addTab(self.Channel3, "")
        self.frame = QFrame(Main)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(310, 10, 401, 121))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.lineEdit_27 = QLineEdit(self.frame)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(10, 20, 91, 31))
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setReadOnly(True)
        self.plainTextEdit = QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(120, 20, 271, 31))
        self.checkBox = QCheckBox(self.frame)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 50, 81, 22))
        self.checkBox_2 = QCheckBox(self.frame)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 90, 81, 22))
        self.checkBox_5 = QCheckBox(self.frame)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(10, 70, 81, 22))
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(90, 60, 80, 24))
        self.pushButton_4 = QPushButton(self.frame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(200, 90, 80, 24))
        self.pushButton_5 = QPushButton(self.frame)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(90, 90, 80, 24))
        self.pushButton_6 = QPushButton(self.frame)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(310, 90, 80, 24))
        self.pushButton_7 = QPushButton(self.frame)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(200, 60, 80, 24))

        self.retranslateUi(Main)

        self.Database_Tab.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Main", None))
        self.Channe2_Reset_pushButton_2.setText(QCoreApplication.translate("Main", u"Reset", None))
        self.lineEdit_6.setText(QCoreApplication.translate("Main", u"Power", None))
        self.lineEdit_7.setText(QCoreApplication.translate("Main", u"Channel 2", None))
        self.lineEdit_8.setText(QCoreApplication.translate("Main", u"Current", None))
        self.Channe2_Start_pushButton_2.setText(QCoreApplication.translate("Main", u"Start", None))
        self.lineEdit_9.setText(QCoreApplication.translate("Main", u"Voltage", None))
        self.lineEdit_10.setText(QCoreApplication.translate("Main", u"Energy", None))
        self.Channe2_Pause_pushButton_2.setText(QCoreApplication.translate("Main", u"Pause", None))
        self.Channe3_Reset_pushButton_3.setText(QCoreApplication.translate("Main", u"Reset", None))
        self.lineEdit_11.setText(QCoreApplication.translate("Main", u"Power", None))
        self.lineEdit_12.setText(QCoreApplication.translate("Main", u"Channel 3 ", None))
        self.lineEdit_13.setText(QCoreApplication.translate("Main", u"Current", None))
        self.Channe3_Start_pushButton_3.setText(QCoreApplication.translate("Main", u"Start", None))
        self.lineEdit_14.setText(QCoreApplication.translate("Main", u"Voltage", None))
        self.lineEdit_15.setText(QCoreApplication.translate("Main", u"Energy", None))
        self.Channe3_Pause_pushButton_3.setText(QCoreApplication.translate("Main", u"Pause", None))
        self.lineEdit_21.setText(QCoreApplication.translate("Main", u"Connection", None))
        self.pushButton.setText(QCoreApplication.translate("Main", u"Connect", None))
        self.pushButton_2.setText(QCoreApplication.translate("Main", u"Refresh", None))
        self.Channe1_Reset_pushButton.setText(QCoreApplication.translate("Main", u"Reset", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Main", u"Power", None))
        self.lineEdit_4.setText(QCoreApplication.translate("Main", u"Channel 1 (USB)", None))
        self.lineEdit_2.setText(QCoreApplication.translate("Main", u"Current", None))
        self.Channe1_Start_pushButton.setText(QCoreApplication.translate("Main", u"Start", None))
        self.lineEdit.setText(QCoreApplication.translate("Main", u"Voltage", None))
        self.lineEdit_5.setText(QCoreApplication.translate("Main", u"Energy", None))
        self.Channe1_Pause_pushButton.setText(QCoreApplication.translate("Main", u"Pause", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Main", u"Time", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Main", u"Voltage", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Main", u"Current", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Main", u"Power", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Main", u"Energy", None));
        self.Database_Tab.setTabText(self.Database_Tab.indexOf(self.Channel1), QCoreApplication.translate("Main", u"Channel 1", None))
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Main", u"Time", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Main", u"Voltage", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Main", u"Current", None));
        ___qtablewidgetitem8 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Main", u"Power", None));
        ___qtablewidgetitem9 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Main", u"Energy", None));
        self.Database_Tab.setTabText(self.Database_Tab.indexOf(self.Channel2), QCoreApplication.translate("Main", u"Channel 2", None))
        ___qtablewidgetitem10 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Main", u"Time", None));
        ___qtablewidgetitem11 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Main", u"Voltage", None));
        ___qtablewidgetitem12 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Main", u"Current", None));
        ___qtablewidgetitem13 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Main", u"Power", None));
        ___qtablewidgetitem14 = self.tableWidget_3.horizontalHeaderItem(4)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Main", u"Energy", None));
        self.Database_Tab.setTabText(self.Database_Tab.indexOf(self.Channel3), QCoreApplication.translate("Main", u"Channel 3", None))
        self.lineEdit_27.setText(QCoreApplication.translate("Main", u"Table Name :", None))
        self.checkBox.setText(QCoreApplication.translate("Main", u"Channel 1", None))
        self.checkBox_2.setText(QCoreApplication.translate("Main", u"Channel 3", None))
        self.checkBox_5.setText(QCoreApplication.translate("Main", u"Channel 2", None))
        self.pushButton_3.setText(QCoreApplication.translate("Main", u"Create", None))
        self.pushButton_4.setText(QCoreApplication.translate("Main", u"Pause", None))
        self.pushButton_5.setText(QCoreApplication.translate("Main", u"Start", None))
        self.pushButton_6.setText(QCoreApplication.translate("Main", u"Clean", None))
        self.pushButton_7.setText(QCoreApplication.translate("Main", u"Delete", None))
    # retranslateUi

